<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="GameDir.targets" Condition="Exists('GameDir.targets')" />

  <PropertyGroup>
    <AssemblyName>BetterUI</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <EnableDefaultCompileItems>False</EnableDefaultCompileItems>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <RootNamespace>BetterUI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="BetterUI\**\*.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>$(BepInExCoreDir)\BepInEx.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(BepInExCoreDir)\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="assembly_valheim">
      <HintPath>publicized\assembly_valheim.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="assembly_guiutils">
      <HintPath>publicized\assembly_guiutils.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="assembly_utils">
      <HintPath>publicized\assembly_utils.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(GameDir)\valheim_Data\Managed\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GameDir)\valheim_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(GameDir)\valheim_Data\Managed\Unity.TextMeshPro.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(GameDir)\valheim_Data\Managed\UnityEngine.UI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(GameDir)\valheim_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(GameDir)\valheim_Data\Managed\UnityEngine.UIModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
